// <auto-generated />
namespace PlanningForm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class WasteLicenceRequired : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207062306439_WasteLicenceRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5dltlwSds+qejGW5h+lx2WRESqv8/L8PfHaeQi8PrI9Up+nhFt7/eZ6lXO/rsvj1aospllLJPBfoFd+r/w6+IA+ellXq7xur1/l5wrm7OlH6d3wvbvdF+1r3jvAhH5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNk3Q2y3kkSpFHq09vR5SHd3f2QJS7NOqqleF2Ee+gSZRpCUuD6+u2JnJ9lD4r3uWz5/nyop1bfL/I3plP9nd2iI2+WhbEb/RWW69zf4Dy9+aOl/TvD7/XbDar86b54XfcVlfLH36vxCpF+cPvts3LfDWvlj8HE/w8v8hKkricprn94Xf/hsSufF20+XGdZzcpgM2gnpVVVX+DYKrzF/nVk3VRwkJYCfh6QPFn1eSzp/llXlarBakrHvk3hPPTfFGVhaivH/YMHtfTeZZXZXVBBsNy0k/9nDDzd7OmzZ8XU7Lr+av8F62LOp/9bGPx+K6zon3bSva+zQqyV8MG9ukTNMrftR1LKwBe5+3wq8SVrnNxCsYxEx5F2KLmfJC74oQYZ+XugLfy+ItstYJQuDf1k/S1uC4n26/f3ztZCIy70ybipFhsbU/kCmQXeedb6powfVbUTfs0a7NJhuk9mS16zb7ORJiuN8xH"
                       + "1zdy02Nexu8hAM+/i85eB6aj9jMiAFQJ00IpQWjewo1TOK9JYrM64oidVOV6sRxy5ja9bf0jH4T98PZwxN3xgcgnt4dgXRcfiP3w9nDEE/GByCe3h6BehQ9CP7o9DM9FCFBxH98eVsfm+/A6X90eZseQ+zA7X90epmcdfXjex18DVtesRyF3G92+n1tYer/HWzS/fd++G+B34n9+e2ibDHsg3Bva3b63uOn2+4m36Pfw+G5HPXZ1smewtWWo7/V7p/A3Gc9uE9u7NaIdY/lYDdfN8X/PkkmTj1Ii3WUxgxV7fU00WYzRYPz6F5Wv85oSHCf5eB9ZC9Psi2xZnNOUvKne5hQs83dfN41gI+ammZX/H8glFEvSYjdmDd7T3bbmTPpYXmYQgTriR76f+yoW7hsG2ongvzG4foD+jQEN4u9vDKpnJL9hyNHo+RuDHg2OmaPfk2F7YeYHAYkHxl8H5C2s39cH3g+Kv7GJuTnm/ca62hTSfs1O3i9i7cdTIb63CFNvG6WKffvso9mkoiEK+vGoNzacDfGsMcV90/v4rp+gf/w0b4oLFxIjXb/Mp+jUGWrT5mx5XpnJouH7GJkmnbn8Im+zGVHxuG6L82za0tdTUs2clvjJrFxTk9PFJJ+dLb9ct6t1e9w0+WJSXvvjfXx3c/8ctIc4P/5yxWT7JoZAaBY0hPzLJSsAi/ezvkQOgQBDqTEmrCgtQ+Auri2kFz3HcQiQku9pvsqXMOVv8sWqJGDNl8vX2WU+jNvNNAwp9vhpkV3U2aJRGO59+pPYj1Z7jv6fAAAA//8dw68rYhoAAA=="; }
        }
    }
}
