// <auto-generated />
namespace PlanningForm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class FloorAreaofNewBuildings : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207061135380_FloorAreaofNewBuildings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5dltlwSds+qejGW5h+lx2WRESqv8/L8PfHaeQi8PrI9Up+nhFt7/eZ6lXO/rsvj1aospllLJPBfoFd+r/w6+IA+ellXq7xur1/l5wrm7OlH6d3wvbvdF+1r3jvAhH5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNk3Q2y3kkSpFHq09vR5SHd3f2QJS7NOqqleF2Ee+gSZRpCUuD6+u2JnJ9lD4r3uWz5/nyop1bfL/I3plP9nd2iI2+WhbEb/RWW69zf4Dy9+aOl/TvD7/XbDar86b54XfcVlfLH36vxCpF+cPvts3LfDWvlj8HE/w8v8hKkricprn94Xf/hsSufF20+XGdZzcpgM2gnpVVVX+DYKrzF/nVk3VRwkJYCbgN0Md3nWLtq1syAW1WkAob1rlPn6BR/q7tKF8B8Dpvh18lRF3nYifGMa0eRdii5szSXbFLxn7dHTBgj7/IVivQyb2pn6SvxZqdbL9+f4O1EBh3p03EbllsbU9kHbKLvPMtdU2YPivqpn2atdkkw3SdzBa9Zl9nIkzXG+ajay7d9JiX8XsIwDP50dnrwHTUfkYEWJAxZFooJQjNW1h2hfN6mpVZHbHNJ1W5XiyH7Pumt63J9EHYD28PRyygD0Q+uT0E"
                       + "a818IPbD28MR4+QDkU9uD0ENjQ9CP7o9DM9qBKi4j28Pq2MGfHidr24Ps6PbfZidr24P01PyPjzv468Bq6vpo5C7jfr9PL7bEcKu5HtmQVuGWkW/d2plk4ruNrG9W1XdUcmPVT3eHHj09KU0+SglAl4WM+jK19dNmy/GaDB+/YvK13lNkdVJPt5HuGSafZEti3NimjfV25y8dP7u68Yv1lVvmln5/4EgpliSrNwYrrynb2KVpvSxvMzq6TyrI07Z+3lhoke/YaCd0OEbg+tHBt8Y0MDx/8ageqr4G4Ycddu/MehRr5w5+j0ZtueTfxCQuEd+M8j388f73mKI3S2c8Nv64KJXP/toNqloNIJ/3Kf/mt56X+U/vutnpB4/zZviwoFAfmqZT9GpA2ranC3PKzM1NHwfI9OkM3Nf5G02Iyoe121xnk1b+npKKoFjy5/MyjU1OV1M8tnZ8st1u1q3x02TLybltT/ex3c3988hSYjz4y9XTLZvYgiEZkFDyL9cMuNZvJ9F2GwABBhKjQBhRbE1gbu4tpBe9Fy1IUBKvqf5Kl/ChLzJF6uSgDVfLl9nl/kwbjfTMKTY46dFdlFni0ZhuPfpT2I/Sm8e/T8BAAD//8QQvQtTFQAA"; }
        }
    }
}
