// <auto-generated />
namespace PlanningForm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class town1 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207041127096_town1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5dltlwSds+qejGW5h+lx2WRESqv8/L8PfHaeQi8PrI9Up+nhFt7/eZ6lXO/rsvj1aospllLJPBfoFd+r/w6+IA+ellXq7xur1/l5wrm7OlH6d3wvbvdF+1r3jvAhH5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNk3Q2y3kkSpFHq09vR5SHd3f2QJS7NOqqleF2Ee+gSZRpCUuD6+u2JnJ9lD4r3uWz5/nyop1bfL/I3plP9nd2iI2+WhbEb/RWW69zf4Dy9+aOl/TvD7/XbDar86b54XfcVlfLH36vxCpF+cPvts3LfDWvlj/rE/z4rhP5viIg5dRmBQnXsDZ4+gSN8ndtRy0IgNd5O/wqMZHrXDTYOKZvoghb1JzCvCsa02jWuwOq9fEX2WpFXXiqVj9JX4uePdl+/f6qdCEw7k6biEa12NqeSG9lF3nnW+qaMH1W1E37NGuzSYbpPZktes2+zkSYrjfMR1eRu+kxL+P3EIBnjKKz14HpqP2MCLAgNc20UEoQmrewOQrn9TQrszpiNU6qcr1YDlmeTW9bZe6DsB/eHo7oZh+IfHJ7CFbP+kDsh7eHI2rTByKf3B6CqkAfhH50exiePgtQcR/3YT2+22GULnd6qktbdjyMLutv"
                       + "UiPdJrZ3q046auOxivDNbltPpqXJRykR6bKYQZ5fXzdtvhijwfj1Lypf5zX5pSf5eB/Opmn2RbYszvOmfVO9zcnH4e++rvdnHZ2mmZX/H3ABi2X7UXqjs9fzEN/LdVteZvV0ntURi/p+1tv3zL4xoB3H6xuD6/tV3xjQwG36xqB66uKDIL+f09M3yQMGdoO83NLREcXw2UezSUVDFPTjjtPXdIn6OuvxXT8gffw0b4oLBwLh6TKfolMH1LQ5W55XZoZo+D5GpklnAr/I22xGVDyu2+I8m7b09ZR4mj3bn8zKNTU5XUzy2dnyy3W7WrfHTZMvJuW1P97Hdzf3z35fiPPjL1dMtm9iCIRmQUPIv1w+WRflzOL9rK9whkCAoVSLEVbk2RO4i2sL6UXPHg4BUvI9zVf5EjrwTb5YlQSs+XL5OrvMh3G7mYYhxR4/LbKLOls0CsO9T38S+1F24+j/CQAA//8QMCShUhEAAA=="; }
        }
    }
}
