// <auto-generated />
namespace PlanningForm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class LegalInterest : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207041139340_LegalInterest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5dltlwSds+qejGW5h+lx2WRESqv8/L8PfHaeQi8PrI9Up+nhFt7/eZ6lXO/rsvj1aospllLJPBfoFd+r/w6+IA+ellXq7xur1/l5wrm7OlH6d3wvbvdF+1r3jvAhH5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNk3Q2y3kkSpFHq09vR5SHd3f2QJS7NOqqleF2Ee+gSZRpCUuD6+u2JnJ9lD4r3uWz5/nyop1bfL/I3plP9nd2iI2+WhbEb/RWW69zf4Dy9+aOl/TvD7/XbDar86b54XfcVlfLH36vxCpF+cPvts3LfDWvlj8HE/w8v8hKkricprn92e7+8V2ncfp6iHRjmxUk28PK6OkTNMrftR2tJABe5+3wq8TDrnNRoOOYuosibFFz+vquKGyj2O8OaPbHX2SrFXXhaXr9JH0tav5k+/X7a/KFwLg7bSIK3WJreyK1mV3knW+pa8L0WVE37dOszSYZpvdktug1+zoTYbreMB9dO+Kmx7yM30MAni2Mzl4HpqP2MyLAgqwE00IpQWjewuQpnNfTrMzqiNE6qcr1Yjlk+Da9bW2JD8J+eHs4Yhp8IPLJ7SFYNe8DsR/eHo5obR+IfHJ7CKqBfRD60e1heOo0QMV9fHtYHf3o"
                       + "w+t81Yf5+G6H+boc76lDbdlxmrritEk1dZvY3q2K6qiix6oWbvZEe3pCmnyUErEuixl0xOvrps0XYzQYv/5F5eu8Jlf7JB/vw382zb7IlsU5EetN9TYnt42/+7oOrfXdmmZW/n/Aqy2WxCM3+q89p/e9vNHlZVZP51kdsdLv5xWI/viGgXZ8yW8Mru8qfmNAA0/wG4PqqaBvGHLUj/ua0N/PTes7ESGit/DNbuuaidr57KPZpKIhCvpxV+9rOnF9jfj4rh/BP36aN8WFA4F4fplP0akDatqcLc8rM0s0fB8j06QziV/kbTYjKh7XbXGeTVv6ekoSw774T2blmpqcLib57Gz55bpdrdvjpskXk/LaH+/ju5v7Z081xPnxlysm2zcxBEKzoCHkXy6frItyZvF+1ldnQyDAUKojCSuKRQjcxbWF9KJnwYcAKfme5qt8CQ37Jl+sSgLWfLl8nV3mw7jdTMOQYo+fFtlFnS0aheHepz+J/SgddPT/BAAA///W7j5bgxIAAA=="; }
        }
    }
}
