// <auto-generated />
namespace PlanningForm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class ArchaeologicalInterestZone : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207062300415_ArchaeologicalInterestZone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5dltlwSds+qejGW5h+lx2WRESqv8/L8PfHaeQi8PrI9Up+nhFt7/eZ6lXO/rsvj1aospllLJPBfoFd+r/w6+IA+ellXq7xur1/l5wrm7OlH6d3wvbvdF+1r3jvAhH5btvf2PkpfrMsym5T0wXlWNvlH6erTR6/bqs4/z5d5nbX57GXWtnlNk3Q2y3kkSpFHq09vR5SHd3f2QJS7NOqqleF2Ee+gSZRpCUuD6+u2JnJ9lD4r3uWz5/nyop1bfL/I3plP9nd2iI2+WhbEb/RWW69zf4Dy9+aOl/TvD7/XbDar86b54XfcVlfLH36vxCpF+cPvts3LfDWvlj8HE/w8v8hKkricprn94Xf/hsSufF20+XGdZzcpgM2gnpVVVX+DYKrzF/nVk3VRwkJYCfh6QPFn1eSzp/llXlarBakrHvk3hPPTfFGVhaivH/YMHtfTeZZXZXVBBsNy0k/9EJj58V1nv/pWjSxtmxVkKYZN29MnaJS/azs2TgC8ztvhV4kfXOdijscx4xlF2KLmrP9dMf/GTbg74Cc8/iJbrcCO7k39JH0tTsPJ9uv39wsWAuPutIm4BxZb2xMZ4ewi73xLXROmz4q6aZ9mbTbJML0ns0Wv2deZCNP1hvnoeiVueszL+D0E4HlW0dnrwHTUfkYE"
                       + "gBAzLZQShOYtHCiF85pkJasjLtBJVa4XyyE3atPb1jPxQdgPbw9HHA0fiHxyewjWafCB2A9vD0d8AB+IfHJ7CGrPfRD60e1heMY5QMV9fHtYHWvrw+t8dXuYHRPqw+x8dXuYnl3y4Xkffw1YXYMahdxtdPt+bmFj/R5v0fz2ffsG2O/E//z20DaZ1EC4N7Tr9/b4bkd5dTWmZ061ZaiN9XunjjeZtm4T27s1cR1T9ljNys1xcc/OSJOPUiLjZTGDjXl93bT5YowG49e/qHyd1xT4n+TjfUTzptkX2bI4J4K9qd7mFETyd183vLaRZNPMyv8PxNjFknTMjdH0e7qh1thIH8vLDAxaR7y893Mxxf58w0A7ke03BtcPXL8xoEFc+o1B9UzYNww5GlV+Y9CjQSNz9HsybC/8+iAg8YDx64C8hW36+sD7weI3NjE3x4Jfs6v3C/X6gUiI9S3iu9uGd2J6PvtoNqloiIJ+PFyMDecWgWDfKj6+6+eUHz/Nm+LCgUCGeZlP0akDatqcLc8rM2U0fB8j06Qzo1/kbTYjKh7XbXGeTVv6ekpak+P5n8zKNTU5XUzy2dnyy3W7WrfHTZMvJuW1P97Hdzf3z9FuiPPjL1dMtm9iCD+ZlQUNIf9yybJp8X7WF5YhEGAotZOEFeUzCNzFtYX0oudxDQFS8j3NV/kSVvZNvliVBKz5cvk6u8yHcbuZhiHFHj8tsos6WzQKw71PfxL70QLF0f8TAAD//zOBpZ0VGQAA"; }
        }
    }
}
